Library_Management_System/Library_Management_System/Controllers/BookActionController.cs
using Library_Management_System.Models.Entity;
using Library_Management_System.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;

namespace Library_Management_System.Controllers
{
    public class BookActionController : Controller
    {
        // GET: BookAction
        BookAction repo = new BookAction();

        Db_Library_ManagementEntities1 db = new Db_Library_ManagementEntities1();

        // ÖDÜNÇ VERME İŞLEMİ
        [HttpGet]
        public ActionResult GiveBookIndex()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GiveBookIndex(TBLACTION p)
        {

            var degerler=db.TBLACTION.Add(p);
            degerler.Durum2 = false;
            db.SaveChanges();

            return RedirectToAction("GiveBookIndex");
        }
        public ActionResult TakeBookIndex()
        {

            var degerler = db.TBLACTION.Where(x=>x.Durum2==false).ToList();
            return View(degerler);
        }

        public ActionResult TakeBook(TBLACTION p)
        {
            var degerler=db.TBLACTION.Find(p.ID);
            DateTime d1 = DateTime.Parse(degerler.ReturnDate.ToString());

            DateTime d2=Convert.ToDateTime(DateTime.Now.ToShortDateString());
            TimeSpan d3 = d2 - d1;

            ViewBag.dgr = d3.TotalDays;
            return View("TakeBook", degerler);

        }

        public ActionResult TakeBookUpdate(TBLACTION p)
        {
            var degerler = db.TBLACTION.Find(p.ID);
            degerler.GetirdigiTarih = p.GetirdigiTarih;
            degerler.Durum2 = true;
            db.SaveChanges();
            return RedirectToAction("TakeBookIndex");

        }
    }
}

Library_Management_System/Library_Management_System/Controllers/BookController.cs
using Library_Management_System.Models.Entity;
using Library_Management_System.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace Library_Management_System.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        BookRepository repo = new BookRepository();
        Db_Library_ManagementEntities1 db = new Db_Library_ManagementEntities1();
        [HttpGet]
        public ActionResult BookIndex(string p)
        {
            var degerler = db.TBLBOOK.ToList();

            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(x => x.Name.ToLower().Contains(p.ToLower())).ToList();
            }
           
            return View(degerler);
        }

        [HttpGet]
        public ActionResult BookAdd()
        {

            List<SelectListItem> deger1 = (from i in db.TBLCATEGORY.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.CategoryAd,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from i in db.TBLAUTHOR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.Name + ' ' + i.Surname,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            return View();
        }

        [HttpPost]

        public ActionResult BookAdd(TBLBOOK p)
        {
            var deger2 = db.TBLCATEGORY.Where(x => x.ID == p.TBLCATEGORY.ID).FirstOrDefault();
            var deger3 = db.TBLAUTHOR.Where(y => y.ID == p.TBLAUTHOR.ID).FirstOrDefault();
            p.TBLCATEGORY = deger2;
            p.TBLAUTHOR = deger3;
            db.TBLBOOK.Add(p);
            db.SaveChanges();
            return RedirectToAction("BookIndex");
        }

        public ActionResult BookDelete(int id)
        {
            var degerler = repo.Find(x => x.ID == id);
            repo.Remove(degerler);
            return RedirectToAction("BookIndex");
        }

        [HttpGet]
        public ActionResult BookFind(int id)
        {
            var degerler = repo.Find(x => x.ID == id);

            List<SelectListItem> deger1 = (from i in db.TBLCATEGORY.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.CategoryAd,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from i in db.TBLAUTHOR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.Name + ' ' + i.Surname,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            return View(degerler);
        }

        [HttpPost]

        public ActionResult BookFind(TBLBOOK p)
        {
            var degerler = db.TBLBOOK.Find(p.ID);
            degerler.ID = p.ID;
            degerler.Name = p.Name;
            degerler.EditionYear = p.EditionYear;
            degerler.PublishingHouse = p.PublishingHouse;
            degerler.Page = p.Page;
            var category = db.TBLCATEGORY.Where(x => x.ID == p.TBLCATEGORY.ID).FirstOrDefault();
            var author = db.TBLAUTHOR.Where(x => x.ID == p.TBLAUTHOR.ID).FirstOrDefault();
            degerler.Category = category.ID;
            degerler.Author = author.ID;
            degerler.Status = true;
            db.SaveChanges();
            return RedirectToAction("BookIndex");
        }
    }
}

Library_Management_System/Library_Management_System/Views/BookAction/GiveBookIndex.cshtml
@model Library_Management_System.Models.Entity.TBLACTION


@{
    ViewBag.Title = "GiveBookIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="color:#915555;font-weight:bold;text-align:center;margin-top:20px;">Emanet Kitap Verme Sayfası</h2>


@using (Html.BeginForm("GiveBookIndex", "BookAction", FormMethod.Post))
{

    <div>
        <label style="color:cadetblue"> ÜYE ID</label>
        @Html.TextBoxFor(x => x.Member, new { @class = "form-control" })


    </div>

    <div>
        <label style="color:cadetblue">KİTAP ID</label>
        @Html.TextBoxFor(x => x.Book, new { @class = "form-control" })

    </div>



    <div>
        <label style="color:cadetblue">PERSONEL ID</label>
        @Html.TextBoxFor(x => x.Employee, new { @class = "form-control" })


    </div>

    <div>
        <label style="color:cadetblue">KİTAP ALIŞ TARİHİ</label>
        <input type="text" name="ShipDate" class="form-control" value="@DateTime.Now.ToShortDateString()" />


    </div>

    <div>
        <label style="color:cadetblue">KİTAP İADE TARİHİ</label>
        <input type="text" name="ReturnDate" class="form-control" value="@DateTime.Now.AddDays(10).ToShortDateString()" />

    </div>
    <br />
    @*<input type="hidden" value="False" name="Durum2" />*@
    <button class="btn btn-primary">Kitabı Emanet Ver</button>

    
}

Library_Management_System/Library_Management_System/Views/BookAction/TakeBook.cshtml
@model Library_Management_System.Models.Entity.TBLACTION
@{
    ViewBag.Title = "TakeBook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2 style="color:#915555;font-weight:bold;text-align:center;margin-top:20px;">İade Etme Sayfası</h2>


@using (Html.BeginForm("TakeBookUpdate", "BookAction", FormMethod.Post))
{


    <div>
        <label>İŞLEM ID</label>
        @Html.TextBoxFor(x => x.ID, new { @class = "form-control", @readonly = "readonly" })

    </div>
    <br />
    <div>
        <label>KİTAP ADI</label>
        @Html.TextBoxFor(x => x.TBLBOOK.Name, new { @class = "form-control", @readonly = "readonly" })

    </div>

    <br />
    <div>
        <label>ÜYE ADI</label>
        @*@Html.TextBoxFor(x => x.TBLMEMBERS.Name, new { @class = "form-control", @readonly = "readonly" })*@
        @Html.TextBox("FullName", Model.TBLMEMBERS.Name + " " + Model.TBLMEMBERS.Surname, new { @class = "form-control", @readonly = "readonly" })

    </div>
    <br />

    <div>
        <label>KİTABI VEREN PERSONEL ADI</label>
        @*@Html.TextBoxFor(x => x.TBLEMPLOYEE.Name, new { @class = "form-control", @readonly = "readonly" })*@
        @Html.TextBox("Employee", Model.TBLEMPLOYEE.Name + " " + Model.TBLEMPLOYEE.Surname, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <br />

    <div>
        <label>KİTAP EMANET VERİLİŞ TARİHİ</label>
        @Html.TextBoxFor(x => x.ShipDate, "{0:dd/MM/yyyy}", new { @class = "form-control", @readonly = "readonly" })

    </div>
    <br />
    <div>
        <label>KİTABIN GERİ VERİLMESİ GEREKEN TARİH</label>
        @Html.TextBoxFor(x => x.ReturnDate, "{0:dd/MM/yyyy}", new { @class = "form-control", @readonly = "readonly" })

    </div>
    <br />
    <div>
        <label>İADE EDİLEN TARİH</label>
        <input type="text" class="form-control" readonly="readonly" name="GetirdigiTarih" value="@DateTime.Now.ToShortDateString()">


    </div>
    <br />
    <label>Geç Gelen Gün Sayısı</label>
    <input type="text" class="form-control" id="gec" value="@ViewBag.dgr" />

    <br />
    <button class="btn btn-primary"> KİTABI GERİ AL</button>







}

Library_Management_System/Library_Management_System/Views/BookAction/TakeBookIndex.cshtml
@using Library_Management_System.Models.Entity
@model List<TBLACTION>
@{
    ViewBag.Title = "TakeBookIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="color:#915555;font-weight:bold;text-align:center;margin-top:20px;">Emanet Kitap Geri Alma Sayfası</h2>

@*@using (Html.BeginForm("Takebbok", "Book", FormMethod.Get))
{
    <div style="margin-bottom:20px; margin-top:20px;">
        <b>Aranıcak kitabı yazınız..&nbsp;</b>@Html.TextBox("p")
        <input type="submit" value=" ARA" class="btn btn-primary" />

    </div>
}*@


<table class="table table-bordered" style="text-align:center;">

    <tr>
        <th>İŞLEM ID</th>
        <th>KİTAP ADI</th>
        <th>ÜYE</th>
        <th>PERSONEL</th>
        <th>ALIŞ TARİHİ</th>
        <th>İADE TARİHİ</th>
        <th>İŞLEM</th>



    </tr>

    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.ID</td>
                <td>@x.TBLBOOK.Name</td>
                <td>@x.TBLMEMBERS.Name&nbsp;@x.TBLMEMBERS.Surname</td>
                <td>@x.TBLEMPLOYEE.Name&nbsp;@x.TBLEMPLOYEE.Surname</td>
                <td>@Convert.ToDateTime(x.ShipDate).ToString("dd/MM/yyyy")</td>
                <td>@Convert.ToDateTime(x.ReturnDate).ToString("dd/MM/yyyy")</td>




                <td>

                    <a href="/BookAction/TakeBook/@x.ID" class="btn btn-primary">Kitabı İade Al</a>





                </td>


            </tr>
        }

        


    </tbody>
</table>






<br />
<br />