Library_Management_System/Library_Management_System/Controllers/BookController.cs
using Library_Management_System.Models.Entity;
using Library_Management_System.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace Library_Management_System.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        BookRepository repo = new BookRepository();
        Db_Library_ManagementEntities1 db = new Db_Library_ManagementEntities1();
        [HttpGet]
        public ActionResult BookIndex(string p)
        {
            var degerler = db.TBLBOOK.ToList();

            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(x => x.Name.ToLower().Contains(p.ToLower())).ToList();
            }
           
            return View(degerler);
        }

        [HttpGet]
        public ActionResult BookAdd()
        {

            List<SelectListItem> deger1 = (from i in db.TBLCATEGORY.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.CategoryAd,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from i in db.TBLAUTHOR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.Name + ' ' + i.Surname,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            return View();
        }

        [HttpPost]

        public ActionResult BookAdd(TBLBOOK p)
        {
            var deger2 = db.TBLCATEGORY.Where(x => x.ID == p.TBLCATEGORY.ID).FirstOrDefault();
            var deger3 = db.TBLAUTHOR.Where(y => y.ID == p.TBLAUTHOR.ID).FirstOrDefault();
            p.TBLCATEGORY = deger2;
            p.TBLAUTHOR = deger3;
            db.TBLBOOK.Add(p);
            db.SaveChanges();
            return RedirectToAction("BookIndex");
        }

        public ActionResult BookDelete(int id)
        {
            var degerler = repo.Find(x => x.ID == id);
            repo.Remove(degerler);
            return RedirectToAction("BookIndex");
        }

        [HttpGet]
        public ActionResult BookFind(int id)
        {
            var degerler = repo.Find(x => x.ID == id);

            List<SelectListItem> deger1 = (from i in db.TBLCATEGORY.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.CategoryAd,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from i in db.TBLAUTHOR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.Name + ' ' + i.Surname,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            return View(degerler);
        }

        [HttpPost]

        public ActionResult BookFind(TBLBOOK p)
        {
            var degerler = db.TBLBOOK.Find(p.ID);
            degerler.ID = p.ID;
            degerler.Name = p.Name;
            degerler.EditionYear = p.EditionYear;
            degerler.PublishingHouse = p.PublishingHouse;
            degerler.Page = p.Page;
            var category = db.TBLCATEGORY.Where(x => x.ID == p.TBLCATEGORY.ID).FirstOrDefault();
            var author = db.TBLAUTHOR.Where(x => x.ID == p.TBLAUTHOR.ID).FirstOrDefault();
            degerler.Category = category.ID;
            degerler.Author = author.ID;
            degerler.Status = true;
            db.SaveChanges();
            return RedirectToAction("BookIndex");
        }
    }
}

Library_Management_System/Library_Management_System/Controllers/StudentPanelController.cs
using Library_Management_System.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Management_System.Controllers
{
   
    public class StudentPanelController : Controller
    {
        // GET: StudentPanel
        Db_Library_ManagementEntities1 db = new Db_Library_ManagementEntities1();

       

        [HttpGet]
        public ActionResult StudentPanelIndex()
        {
            var degerler1 = (string)Session["Mail"];
            var uye1 = db.TBLMEMBERS.FirstOrDefault(x => x.Mail == degerler1);
            return View(uye1);
        }
        [HttpPost]
        public ActionResult StudentPanelIndex(TBLMEMBERS p)
        {
            var degerler = (string)Session["Mail"];
            var uye = db.TBLMEMBERS.FirstOrDefault(x => x.Mail == degerler);
            uye.Password = p.Password;
            db.SaveChanges();
            return View();
        }

        public ActionResult Books()
        {
            var kullanici = (string)Session["Mail"];
            var id=db.TBLMEMBERS.Where(x=>x.Mail==kullanici.ToString()).Select(z=>z.ID).FirstOrDefault();

            var degerler=db.TBLACTION.Where(x=>x.Member==id).ToList();

            return View(degerler);
        }
    }
}

Library_Management_System/Library_Management_System/Views/StudentPanel/Books.cshtml
@using Library_Management_System.Models.Entity
@model List<TBLACTION>
@{
    ViewBag.Title = "Books";
    Layout = "~/Views/Shared/_StudentPanelLayout.cshtml";
}


<br />
<h2>Kitap Geçmişim</h2>
<br />


<table class="table table-bordered" style="text-align:center;">

    <tr>

        <th>KİTAP ADI</th>


        <th>ALIŞ TARİHİ</th>
        <th>VERMESİ GEREKEN TARİH</th>
        <th>GETİRDİĞİ TARİHİ</th>
        




    </tr>

    <tbody>
            @foreach (var x in Model)
            {
                <tr>
                  
                    <td>@x.TBLBOOK.Name</td>
                    
                  
                    <td>@Convert.ToDateTime(x.ShipDate).ToString("dd/MM/yyyy")</td>
                    <td>@Convert.ToDateTime(x.ReturnDate).ToString("dd/MM/yyyy")</td>
                    <td>@Convert.ToDateTime(x.GetirdigiTarih).ToString("dd/MM/yyyy")</td>
                    


                </tr>
            }




        </tbody>
</table>






<br />
<br />

Library_Management_System/Library_Management_System/Views/StudentPanel/StudentPanelIndex.cshtml
@model Library_Management_System.Models.Entity.TBLMEMBERS
@{
    ViewBag.Title = "StudentPanelIndex";
    Layout = "~/Views/Shared/_StudentPanelLayout.cshtml";
}
<br />
<h2>Öğrenci Panelim</h2>
<br />

@using (Html.BeginForm("StudentPanelIndex", "StudentPanel", FormMethod.Post))
{
    <table class="table table-bordered">

        <tr>
            <td>
                <label style="font-weight:bold">Mail Adresi:</label>
                @HttpContext.Current.User.Identity.Name

            </td>

        </tr>

        <tr>
            <td>
                @*<label style="font-weight:bold">Ad:</label>
                @TempData["Name"].ToString()*@
                <label>Ad</label>
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" ,@readonly="readonly"})

            </td>

        </tr>

        <tr>
            <td>
                @*<label style="font-weight:bold">Soyad:</label>
                @TempData["Surname"].ToString()*@
                <label>Soyad</label>
                @Html.TextBoxFor(x => x.Surname, new { @class = "form-control", @readonly = "readonly" })

            </td>

        </tr>





        <tr>
            <td>
                @*<label style="font-weight:bold">Şifre:</label>
        <input type="text" class="form-control" value="@TempData["Password"].ToString()" name="Password" />*@

                <label>Şifre</label>
                @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
            </td>

        </tr>

        <tr>
            <td>
                <!--<label style="font-weight:bold">Okul:</label>-->
                @*@TempData["School"].ToString()*@

                <label>Okul</label>
                @Html.TextBoxFor(x => x.School, new { @class = "form-control", @readonly = "readonly" })

            </td>

        </tr>



        <tr>
            <td>
                <button class="btn btn-warning">Şifre Güncelle</button>

            </td>

        </tr>
    </table>
}